name: Play Mode Test

on:
  workflow_dispatch:
  push:

jobs:
  play-mode-test:
    runs-on: [self-hosted, dev-pc-windows]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run tests
        uses: game-ci/unity-test-runner@v2.0.3
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE_2021_3_3F1 }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          unityVersion: 2021.3.6f1
          projectPath: UXSim
